version: "3.5"
services:
  rcore_nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/rcore
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/nginx/cert/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./etc/nginx/cert/localhost.key:/etc/ssl/private/localhost.key
    networks:
      - rcore_network
    depends_on:
      - rcore_phpfpm

  rcore_phpfpm:
    build:
      dockerfile: ./dockerfiles/phpfpm/Dockerfile
    volumes:
      - .:/rcore
      - rcore-cachevolume:/data
    working_dir: /rcore
    networks:
      - rcore_network

  rcore_mysql:
    image: mysql:latest
    volumes:
      - rcore-datavolume:/data/mysql
    networks:
      - rcore_network
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password

  rcore_pma:
    image: phpmyadmin/phpmyadmin
    volumes:
      - ./etc/pma/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    networks:
      - rcore_network
    depends_on:
      - rcore_mysql
    environment:
      PMA_HOST: rcore_mysql
      PMA_ABSOLUTE_URI: http://localhost/pma/

  rcore_metricize_redis:
    image: redis
    ports:
      - "6380:6380"
    networks:
      - rcore_network

  rcore_metricize_prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - rcore-prometheus-storage:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - rcore_nginx
      - rcore_metricize_nginx_exporter
      - rcore_metricize_node_exporter
    networks:
      - rcore_network

  rcore_metricize_grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./vendor/rudolfspumpurs/metricize/grafana.ini:/etc/grafana/grafana.ini
      - ./vendor/rudolfspumpurs/metricize/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./vendor/rudolfspumpurs/metricize/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./vendor/rudolfspumpurs/metricize/standardized-dashboard.json:/var/lib/grafana/dashboards/standardized-dashboard.json
      - rcore-grafana-storage:/var/lib/grafana
    depends_on:
      - rcore_metricize_prometheus
    networks:
      - rcore_network

  rcore_metricize_nginx_exporter:
    image: nginx/nginx-prometheus-exporter
    ports:
      - "9113:9113"
    command:
      - -nginx.scrape-uri
      - http://rcore_nginx/nginx_status
    depends_on:
      - rcore_nginx
    networks:
      - rcore_network

  rcore_metricize_node_exporter:
    image: prom/node-exporter:latest
    networks:
      - rcore_network

  rcore_metricize_php_fpm_exporter:
    image: hipages/php-fpm_exporter:latest
    ports:
      - "9253:9253"
    environment:
      PHP_FPM_SCRAPE_URI: "tcp://rcore_phpfpm:9000/status"
      PHP_FPM_LOG_LEVEL: "debug"
    networks:
      - rcore_network

networks:
  rcore_network:
    driver: bridge

volumes:
  rcore-datavolume:
  rcore-cachevolume:
  rcore-grafana-storage:
  rcore-prometheus-storage: