# global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'metricize'
    static_configs:
      - targets: ['rcore_nginx']

  - job_name: 'nginx'
    static_configs:
      - targets: [ 'rcore_metricize_nginx_exporter:9113' ]

  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'rcore_metricize_node_exporter:9100' ]

  - job_name: 'php-fpm'
    static_configs:
      - targets: [ 'rcore_metricize_php_fpm_exporter:9253' ]